/*
	C verion of NP03 detector simulation program.
	To compile: gcc -o np03r np03r.c -lm
	To run:	 ./np03r inputfile outputfile

	The files contain a series of events generated by the GEANT4 simulation program.
	The simulation is an infinite block of either Silicon or Germanium.	Photons
	are generated at the origin pointing along the positive x axis.	The simulation
	generates the interactions in the following particle cascade.	We are going to
	make two simplifying assumptions to avoid the computing becoming too complicted.
	(1) The electron and positrons deposit their energy all in one location as soon
		as they are generated.	This is almost true, they usually travel a few 
		tens of microns to deposit their energy.
	(2) We neglect tertiary bremstrahlung - i.e. the process where electrons emit 
		photons (which move a large distance) before making electrons again.	This
		is not bad either - in reality <1% of events have a bremstrahlung.	In the
		files, the energy of the bremstrahlung photon is added in to the electron
		which made it.
	This means that the events in the files almost always contain a single chain of
	electrons which have been knocked off by the primary photon.	The exception to
	this is pair production.
 
	There are four versions of the input files simulated with different parameters
	the variations in their file names are given here in brackets.
	Two of the files are simulated with Silicon (Si), and two with Germanium (Ge).
	Two start with monoenergetic 'Cesium' photons E=0.6617MeV (Cs) and the other
	two have photons with random energies uniformly from 0.030MeV to 3.030MeV (All) 

	The next clump of comments document the input file format in too much detail 
	to begin with.	You don't need to know all the detail to start, probably.	The 
	program loops over the events and reads them in.	Better start by looking at the 
	comments in the loop which gives the meaning of the variables which have been read.

	Here is an example of an event.	It contains a series of 'E' lines followed by
	one 'M' line which indicates the end of the event.	The 'E' lines represent a 
	particle within one interaction.	The 3 numbers in the 1st bracket are (x,y,z)
	of the end of the first step the particle made (we think it is where it first 
	interacts?). The next 4 numbers are also in brackets and are not used (except 
	that the first 3 are a repeat of the x,y,z of the parent particle).	The final six
	bits of information are partice-type particle-energy ignore-next partID parentID 
	interact-code.	The one to ignore is the energy loss inside the GEANT step.	This
	is not useful without more info from GEANT because it can step the particle 
	more than once.
	Energies are in MeV.	Distances are in mm (must check the mm).
	The interact-code is compt=compton scatter, conv=pair production (aka conversion)
	phot=photoelectric.	For the photon, it gives the first interaction which happened.
	The interact-code of the electron is usually eIoni=Electron ionisation.
 
E (103.595025,0.000000,0.000000) (0.000000,0.000000,0.000000,0.000000) gamma 0.661700 0.000000 1 0 compt
E (110.054005,129.214988,-29.651278) (103.595025,0.000000,0.000000,103.595025) e- 0.052832 0.052832 11 1 eIoni
E (104.175232,126.425472,-27.431369) (103.595025,0.000000,0.000000,103.595025) e- 0.002926 0.002926 10 1 eIoni
E (104.103995,123.438379,-24.163798) (103.595025,0.000000,0.000000,103.595025) e- 0.014981 0.014981 9 1 eIoni
E (104.992130,124.195952,-25.239895) (103.595025,0.000000,0.000000,103.595025) e- 0.028011 0.028011 8 1 eIoni
E (100.363148,119.641707,-21.950251) (103.595025,0.000000,0.000000,103.595025) e- 0.058091 0.058091 7 1 eIoni
E (104.220751,127.052374,-33.705091) (103.595025,0.000000,0.000000,103.595025) e- 0.140492 0.140492 6 1 eIoni
E (114.121669,96.487046,-29.259889) (103.595025,0.000000,0.000000,103.595025) e- 0.018915 0.018915 5 1 eIoni
E (143.836794,59.362828,-7.262470) (103.595025,0.000000,0.000000,103.595025) e- 0.054741 0.054741 4 1 eIoni
E (143.944857,31.562242,-3.126021) (103.595025,0.000000,0.000000,103.595025) e- 0.145172 0.145172 3 1 eIoni
E (103.624575,-0.036994,0.003667) (103.595025,0.000000,0.000000,103.595025) e- 0.143694 0.143694 2 1 eIoni
M 0 0.661700 gamma compt 0.659855 0.997212 -0.001845

 The numbers on the 'M' line are: event-number first-particle-energy first-particle-type
 first-interaction-of-first-particle sum-of-all-secondary-energy.	The last two give the
 discrepancy between the first-particle-energy and the sum-of-all-secondary-energy, 
 the first as a fraction, the second as a difference.	The difference seems to be
 the more consistent, perhaps there is some atomic binding energy or something.
 If there was a pair production, the rest mass energy of the e+e- is not included in
 the total.
*/

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>

#define NBINS 300

int main(int argc, char** argv) {
	char infile[1000],outfile[1000];
	FILE *inf,*ouf;
	float tener;

// ***Place to modify*** Reserve space for histograms

	int henerall[NBINS] = {0}, henerpeak[NBINS] = {0}, htener[NBINS] = {0}, ibb;

	// Check correct arguments
	if (argc != 3) {
	printf("usage: %s <in-text-file> <out-text-file>\n",argv[0]);
	exit(1);
	}

	strncpy(infile ,argv[1],sizeof(infile));
	strncpy(outfile,argv[2],sizeof(outfile));

	// Open input text file
	if (infile[0] == '-' && infile[1] == '\0') { inf = stdin; }
	else { inf = fopen(infile,"r"); }
	if (!inf) {
		printf("Input file %s cannot be opened\n",infile);
		exit(1);
	}

	// Open output file
	if (outfile[0] == '-' && outfile[1] == '\0') { ouf = stdout; }
	else { ouf = fopen(outfile,"w"); }
	if (!ouf) {
		printf("Output file %s cannot be opened\n",outfile);
		exit(1);
	}

	// Main loop
	tener = 0.;	// Variable for total energy detected
	while (1) {	 // Infinite loop, exit with break statement below
		char line[1000],*rc;

		rc = fgets(line,1000,inf);	// Read a line in ended with \n or EOF
		if (feof(inf)) break;		 // feof returns true when end of file

		// An E line.	 Unpack and add energy to total if wanted
		if (line[0] == 'E') {
		char spart[100],sinter[100];
		float sx,sy,sz,spx,spy,spz,spr,sener,sdener;
		int sid,spid;

		sscanf(line,"%*c (%f,%f,%f) (%f,%f,%f,%f) %99s %f %f %d %d %99s", 
			&sx,&sy,&sz,&spx,&spy,&spz,&spr,spart,&sener,&sdener,&sid,&spid,sinter);

		 // sx		x position of step (mm)
		 // sy		y position of step (mm)
		 // sz		z position of step (mm)
		 // spx		 x position of photon in it's step (mm)
		 // spy		 y position of photon in it's step (mm)
		 // spz		 z position of photon in it's step (mm)
		 // spart	 Particle name 'gamma', 'e-' or 'e+'
		 // sener	 Particle energy (MeV)
		 // sid		 Particle ID (1=primary photon)
		 // spid		Particle ID of parent
		 // sinter	Inteaction-code (see above)
				 
		// ***Place to modify***	Decide whether to add in the energy
		if (spart[0] == 'e' &&		// Only e+ and e-, not photons
			 sqrt(sy*sy+sz*sz)<30. &&	// radius 3cm
			 sx > 0. && sx < 100.) {	 // 10cm long
			 tener = tener + sener;
		}
		} // End of 'E' line processing

		// An 'M' line.	Process the event, and reset total for next
		if (line[0] == 'M') {
		int mevno,ib,ibt;
		float mener,menert,mratio,mdifference,d;
		char mpart[100],minter[100];

		sscanf(line,"%*c %d %f %99s %99s %f %f %f",
			&mevno,&mener,mpart,minter,&menert,&mratio,&mdifference);

		 // mevno	 Event number
		 // mener	 Energy of photon
		 // mpart	 Particle type of primary (should be 'photon')
		 // minter	First interaction of primary usually 'conv', 'compt' or 'phot'
		 // menert	Total energy of secondaries

		// ***Place to modify***	Histogram filling
		// Make an integer which is the bin number from 0 to NBINS-1 for E=0 to 3
		// Put events above 3MeV in bin NBINS-1
		 ib = (mener*NBINS/3.0);
		 //printf("mener = %f calc = %f ib = %d\n",mener,mener/3.0*NBINS,ib);
		 if (ib < 0) { ib = 0; }
		 if (ib >= NBINS) { ib = NBINS-1; }

		 henerall[ib] = henerall[ib] + 1;		 
		 d = tener - mener;	 // Difference in energy (nearly 0 if on peak)
		 if (d > -0.02 && d < 0.02) { henerpeak[ib] = henerpeak[ib] + 1; }

		 // Similar bin calculation to above for tener
		 ibt = (tener/3.0*NBINS);
		 if (ibt < 0) { ibt = 0; }
		 if (ibt >= NBINS) { ibt = NBINS-1; }
		 htener[ibt] = htener[ibt] + 1;

		 // Reset variables which are accumulted in the E lines for next event
		 tener = 0.;

		 // Print occasionally so we know it is running
		 if (mevno%10000 == 0) { printf("Just done event %d\n",mevno); }
		} // End of 'M' line processing		
	} // End of loop.

	// Now write a table from histograms to output file
	for (ibb=0; ibb<NBINS; ibb++) {
	 float e;
	 e = ibb*3.0/NBINS;	 // Invert the ib calculation above to get energy at bottom edge of bin
	 fprintf(ouf,"%f %5d %5d %5d\n",e,henerall[ibb],henerpeak[ibb],htener[ibb]);
	}

	fclose(inf);
	fclose(ouf);
}

